"""add hidden_from_notes to study session

Revision ID: 656cbc8a31f3
Revises: a992315fd5f6
Create Date: 2026-03-08 18:01:09.424861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656cbc8a31f3'
down_revision = 'a992315fd5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_from_notes', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('hidden_from_notes')

    # ### end Alembic commands ###
