"""add source to study_session

Revision ID: 82684c8a868d
Revises: a310b373907e
Create Date: 2026-08-16 23:03:23.482601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82684c8a868d'
down_revision = 'a310b373907e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10), server_default='free', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
