"""add parse rate limit columns to user

Revision ID: a310b373907e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-16 18:06:30.181250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a310b373907e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('parse_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('parse_count')
        batch_op.drop_column('parse_date')

    # ### end Alembic commands ###
