"""remove source from study_session

Revision ID: d171f007c25f
Revises: 82684c8a868d
Create Date: 2026-08-17 20:37:07.145568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd171f007c25f'
down_revision = '82684c8a868d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=10), server_default=sa.text("'free'"), nullable=False))

    # ### end Alembic commands ###
