"""add email reminders to user

Revision ID: eab76c13629f
Revises: 6e3647ed3f5f
Create Date: 2026-08-25 17:11:12.580566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab76c13629f'
down_revision = '6e3647ed3f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_reminders', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reminder_timing', sa.String(length=10), server_default='1day', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reminder_timing')
        batch_op.drop_column('email_reminders')

    # ### end Alembic commands ###
